In [1]:
import pandas as pd 
import numpy as np
import matplotlib
%matplotlib inline
import seaborn as sns 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import random


In [2]:
pd.set_option('display.width',200)
data = pd.read_csv('C:\\Noble\\Training\\inventateq\\Data Science\\DS and ML\\05 Feb Class Room\Data\\pacific.csv')
print (data.head())


         ID                 Name      Date  Time Event Status Latitude Longitude  Maximum Wind  Minimum Pressure  ...  Low Wind SW  Low Wind NW  Moderate Wind NE  Moderate Wind SE  Moderate Wind SW  \
0  EP011949              UNNAMED  19490611     0           TS    20.2N    106.3W            45              -999  ...         -999         -999              -999              -999              -999   
1  EP011949              UNNAMED  19490611   600           TS    20.2N    106.4W            45              -999  ...         -999         -999              -999              -999              -999   
2  EP011949              UNNAMED  19490611  1200           TS    20.2N    106.7W            45              -999  ...         -999         -999              -999              -999              -999   
3  EP011949              UNNAMED  19490611  1800           TS    20.3N    107.7W            45              -999  ...         -999         -999              -999              -999              -99

In [3]:
display (data)

ID                 Name      Date  Time Event Status Latitude Longitude  Maximum Wind  Minimum Pressure  ...  Low Wind SW  Low Wind NW  Moderate Wind NE  Moderate Wind SE  \
0      EP011949              UNNAMED  19490611     0           TS    20.2N    106.3W            45              -999  ...         -999         -999              -999              -999   
1      EP011949              UNNAMED  19490611   600           TS    20.2N    106.4W            45              -999  ...         -999         -999              -999              -999   
2      EP011949              UNNAMED  19490611  1200           TS    20.2N    106.7W            45              -999  ...         -999         -999              -999              -999   
3      EP011949              UNNAMED  19490611  1800           TS    20.3N    107.7W            45              -999  ...         -999         -999              -999              -999   
4      EP011949              UNNAMED  19490612     0           TS    20.4N    108.6W            45              -999  ...         -999         -999              -999              -999   
...         ...                  ...       ...   ...   ...    ...      ...       ...           ...               ...  ...          ...          ...               ...               ...   
26132  EP222015               SANDRA  20151128  1200           LO    21.7N    109.0W            35              1002  ...            0            0                 0                 0   
26133  EP222015               SANDRA  20151128  1800           LO    22.4N    108.7W            30              1007  ...            0            0                 0                 0   
26134  EP222015               SANDRA  20151129     0           LO    23.1N    108.3W            30              1008  ...            0            0                 0                 0   
26135  EP222015               SANDRA  20151129   600           LO    23.5N    107.9W            25              1009  ...            0            0                 0                 0   
26136  EP222015               SANDRA  20151129  1200           LO    24.2N    107.7W            20              1010  ...            0            0                 0                 0   

       Moderate Wind SW  Moderate Wind NW  High Wind NE  High Wind SE  High Wind SW  High Wind NW  
0                  -999              -999          -999          -999          -999          -999  
1                  -999              -999          -999          -999          -999          -999  
2                  -999              -999          -999          -999          -999          -999  
3                  -999              -999          -999          -999          -999          -999  
4                  -999              -999          -999          -999          -999          -999  
...                 ...               ...           ...           ...           ...           ...  
26132                 0                 0             0             0             0             0  
26133                 0                 0             0             0             0             0  
26134                 0                 0             0             0             0             0  
26135                 0                 0             0             0             0             0  
26136                 0                 0             0             0             0             0  

[26137 rows x 22 columns]

In [4]:
data.groupby('Status').agg({'Status': np.size})

Status
Status        
 DB        217
 ET        152
 EX        110
 HU       6766
 LO       1828
 PT          6
 SD          4
 SS          7
 ST          6
 TD       6965
 TS      10076

In [5]:
data.Status = pd.Categorical(data.Status)
data['Status'] = data.Status.cat.codes
data.head()


ID                 Name      Date  Time Event  Status Latitude Longitude  Maximum Wind  Minimum Pressure  ...  Low Wind SW  Low Wind NW  Moderate Wind NE  Moderate Wind SE  \
0  EP011949              UNNAMED  19490611     0            10    20.2N    106.3W            45              -999  ...         -999         -999              -999              -999   
1  EP011949              UNNAMED  19490611   600            10    20.2N    106.4W            45              -999  ...         -999         -999              -999              -999   
2  EP011949              UNNAMED  19490611  1200            10    20.2N    106.7W            45              -999  ...         -999         -999              -999              -999   
3  EP011949              UNNAMED  19490611  1800            10    20.3N    107.7W            45              -999  ...         -999         -999              -999              -999   
4  EP011949              UNNAMED  19490612     0            10    20.4N    108.6W            45              -999  ...         -999         -999              -999              -999   

   Moderate Wind SW  Moderate Wind NW  High Wind NE  High Wind SE  High Wind SW  High Wind NW  
0              -999              -999          -999          -999          -999          -999  
1              -999              -999          -999          -999          -999          -999  
2              -999              -999          -999          -999          -999          -999  
3              -999              -999          -999          -999          -999          -999  
4              -999              -999          -999          -999          -999          -999  

[5 rows x 22 columns]

In [6]:
data.groupby('Status').agg({'Status': np.size})

Status
Status        
0          217
1          152
2          110
3         6766
4         1828
5            6
6            4
7            7
8            6
9         6965
10       10076

In [7]:
pred_columns = data[:]
pred_columns.drop(['Status'],axis=1,inplace=True)
pred_columns.drop(['Event'],axis=1,inplace=True)
pred_columns.drop(['Latitude'],axis=1,inplace=True)
pred_columns.drop(['Longitude'],axis=1,inplace=True)
pred_columns.drop(['ID'],axis=1,inplace=True)
pred_columns.drop(['Name'],axis=1,inplace=True)
pred_columns.drop(['Date'],axis=1,inplace=True)
pred_columns.drop(['Time'],axis=1,inplace=True)
prediction_var = pred_columns.columns
print(list(prediction_var))


['Maximum Wind', 'Minimum Pressure', 'Low Wind NE', 'Low Wind SE', 'Low Wind SW', 'Low Wind NW', 'Moderate Wind NE', 'Moderate Wind SE', 'Moderate Wind SW', 'Moderate Wind NW', 'High Wind NE', 'High Wind SE', 'High Wind SW', 'High Wind NW']


C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [8]:
data.isnull().sum()

ID                  0
Name                0
Date                0
Time                0
Event               0
Status              0
Latitude            0
Longitude           0
Maximum Wind        0
Minimum Pressure    0
Low Wind NE         0
Low Wind SE         0
Low Wind SW         0
Low Wind NW         0
Moderate Wind NE    0
Moderate Wind SE    0
Moderate Wind SW    0
Moderate Wind NW    0
High Wind NE        0
High Wind SE        0
High Wind SW        0
High Wind NW        0
dtype: int64

In [9]:
from sklearn.model_selection  import train_test_split
train, test = train_test_split(data, test_size = 0.3)
print(train.shape)
print(test.shape)


(18295, 22)
(7842, 22)


In [10]:
train_x = train[prediction_var]
train_y= train['Status']  
print(list(train.columns))
print(train_x.shape)
print(train_y.shape)


['ID', 'Name', 'Date', 'Time', 'Event', 'Status', 'Latitude', 'Longitude', 'Maximum Wind', 'Minimum Pressure', 'Low Wind NE', 'Low Wind SE', 'Low Wind SW', 'Low Wind NW', 'Moderate Wind NE', 'Moderate Wind SE', 'Moderate Wind SW', 'Moderate Wind NW', 'High Wind NE', 'High Wind SE', 'High Wind SW', 'High Wind NW']
(18295, 14)
(18295,)


In [11]:
train_x.shape

(18295, 14)

In [12]:
test_x= test[prediction_var] 
test_y =test['Status']
print(list(test.columns))
print(test_x.shape)
print(test_y.shape)


['ID', 'Name', 'Date', 'Time', 'Event', 'Status', 'Latitude', 'Longitude', 'Maximum Wind', 'Minimum Pressure', 'Low Wind NE', 'Low Wind SE', 'Low Wind SW', 'Low Wind NW', 'Moderate Wind NE', 'Moderate Wind SE', 'Moderate Wind SW', 'Moderate Wind NW', 'High Wind NE', 'High Wind SE', 'High Wind SW', 'High Wind NW']
(7842, 14)
(7842,)


In [13]:
test_x

Maximum Wind  Minimum Pressure  Low Wind NE  Low Wind SE  Low Wind SW  Low Wind NW  Moderate Wind NE  Moderate Wind SE  Moderate Wind SW  Moderate Wind NW  High Wind NE  High Wind SE  \
14735           100               960         -999         -999         -999         -999              -999              -999              -999              -999          -999          -999   
23277            25              1010            0            0            0            0                 0                 0                 0                 0             0             0   
5563             35              -999         -999         -999         -999         -999              -999              -999              -999              -999          -999          -999   
26134            30              1008            0            0            0            0                 0                 0                 0                 0             0             0   
6073             25              -999         -999         -999         -999         -999              -999              -999              -999              -999          -999          -999   
...             ...               ...          ...          ...          ...          ...               ...               ...               ...               ...           ...           ...   
23038            65               987           70           70           50           70                30                30                25                30            15            15   
24599           105               958           80           70           60           70                40                40                40                40            20            20   
22508            25              1007            0            0            0            0                 0                 0                 0                 0             0             0   
18047            25              1006         -999         -999         -999         -999              -999              -999              -999              -999          -999          -999   
10672            45              -999         -999         -999         -999         -999              -999              -999              -999              -999          -999          -999   

       High Wind SW  High Wind NW  
14735          -999          -999  
23277             0             0  
5563           -999          -999  
26134             0             0  
6073           -999          -999  
...             ...           ...  
23038            10            15  
24599            15            20  
22508             0             0  
18047          -999          -999  
10672          -999          -999  

[7842 rows x 14 columns]

In [14]:
test_y

14735     3
23277     4
5563     10
26134     4
6073      9
         ..
23038     3
24599     3
22508     4
18047     9
10672    10
Name: Status, Length: 7842, dtype: int8

In [15]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(train_x, train_y)
log_pred = logmodel.predict(data[prediction_var])
print (log_pred)
print (pd.DataFrame(log_pred).groupby(0).agg({0: np.size}))
print('\n Accuracy Score')
print (accuracy_score (data['Status'],log_pred))
print('\nClassification Report')
print(classification_report (data['Status'],log_pred))
print('Confusion Matrix')
print (confusion_matrix (data['Status'],log_pred))


[10 10 10 ...  4  4  4]
        0
0        
3    6813
4    2985
9    5619
10  10720

 Accuracy Score
0.7632092436010254

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       0.86      0.86      0.86      6766
           4       0.55      0.91      0.69      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.00      0.00      0.00         6
           9       0.76      0.62      0.68      6965
          10       0.76      0.81      0.78     10076

    accuracy                           0.76     26137
   macro avg       0.27      0.29      0.27     26137
weighted avg       0.76      0.76      0.76     26137

Confusion Matrix
[[   0    0    0    0  217 

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in l

In [16]:
from sklearn.neighbors import KNeighborsClassifier
KNN1 = KNeighborsClassifier(n_neighbors =100 , metric = 'minkowski', p= 2)
KNN1.fit(train_x,train_y)
KNN1_pred = KNN1.predict(data[prediction_var])
print (KNN1_pred)
print (pd.DataFrame(KNN1_pred).groupby(0).agg({0: np.size}))
print('\n Accuracy Score')
print (accuracy_score (data['Status'],KNN1_pred))
print('\nClassification Report')
print(classification_report (data['Status'],KNN1_pred))
print('Confusion Matrix')
print (confusion_matrix (data['Status'],KNN1_pred))



[10 10 10 ...  9  4  4]
        0
0        
3    6804
4    1966
9    7225
10  10142

 Accuracy Score
0.9508742395837319

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       0.99      0.99      0.99      6766
           4       0.74      0.79      0.77      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.00      0.00      0.00         6
           9       0.92      0.96      0.94      6965
          10       0.99      0.99      0.99     10076

    accuracy                           0.95     26137
   macro avg       0.33      0.34      0.34     26137
weighted avg       0.93      0.95      0.94     26137

Confusion Matrix
[[    0     0     0     0  

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [17]:
from sklearn.neighbors import KNeighborsClassifier
KNN2 = KNeighborsClassifier(n_neighbors =100 , metric = 'minkowski', p= 1)
KNN2.fit(train_x,train_y)
KNN2_pred = KNN2.predict(data[prediction_var])
print (KNN2_pred)
print (pd.DataFrame(KNN2_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (data['Status'],KNN2_pred))
print('\nClassification Report')
print(classification_report (data['Status'],KNN2_pred))
print('Confusion Matrix')
print (confusion_matrix (data['Status'],KNN2_pred))


[10 10 10 ...  9  4  4]
        0
0        
3    6771
4    1956
9    7247
10  10163

 Accuracy Score
0.9520602976623178

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       0.99      0.99      0.99      6766
           4       0.74      0.79      0.77      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.00      0.00      0.00         6
           9       0.92      0.96      0.94      6965
          10       0.99      1.00      0.99     10076

    accuracy                           0.95     26137
   macro avg       0.33      0.34      0.34     26137
weighted avg       0.94      0.95      0.94     26137

Confusion Matrix
[[    0     0     0     0  

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [18]:
from sklearn.naive_bayes import GaussianNB
GNB= GaussianNB()
GNB.fit(train_x,train_y)
GNB_pred = GNB.predict(data[prediction_var])
print (GNB_pred)
print (pd.DataFrame(GNB_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (data['Status'],GNB_pred))
print('\nClassification Report')
print(classification_report (data['Status'],GNB_pred))
print('Confusion Matrix')
print (confusion_matrix (data['Status'],GNB_pred))


[1 1 1 ... 0 0 0]
        0
0        
0    2977
1   19729
3    1052
4       9
5     239
6      35
7    1862
8      19
10    215

 Accuracy Score
0.05543865018938669

Classification Report
              precision    recall  f1-score   support

           0       0.07      1.00      0.14       217
           1       0.01      1.00      0.02       152
           2       0.00      0.00      0.00       110
           3       1.00      0.16      0.27      6766
           4       0.00      0.00      0.00      1828
           5       0.01      0.33      0.02         6
           6       0.06      0.50      0.10         4
           7       0.00      1.00      0.01         7
           8       0.26      0.83      0.40         6
           9       0.00      0.00      0.00      6965
          10       0.06      0.00      0.00     10076

    accuracy                           0.06     26137
   macro avg       0.13      0.44      0.09     26137
weighted avg       0.28      0.06      0.07     26137


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [19]:
from sklearn.naive_bayes import BernoulliNB
BNB = BernoulliNB()
BNB.fit(train_x,train_y)
BNB_pred = BNB.predict(data[prediction_var])
print (BNB_pred)
print (pd.DataFrame(BNB_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (data['Status'],BNB_pred))
print('\nClassification Report')
print(classification_report (data['Status'],BNB_pred))
print('Confusion Matrix')
print (confusion_matrix (data['Status'],BNB_pred))	


[9 9 9 ... 9 9 9]
        0
0        
3      19
7     661
8    1235
9   22770
10   1452

 Accuracy Score
0.3204269809082909

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       0.00      0.00      0.00      6766
           4       0.00      0.00      0.00      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.29      0.01         7
           8       0.00      1.00      0.01         6
           9       0.31      1.00      0.47      6965
          10       0.97      0.14      0.24     10076

    accuracy                           0.32     26137
   macro avg       0.12      0.22      0.07     26137
weighted avg       0.45      0.32      0.22     26137

Confusion Matrix
[[   0    0    0    0  

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [20]:
from sklearn.preprocessing import MinMaxScaler
MMS = MinMaxScaler()
MMS_train_x = MMS.fit_transform(train_x)
MMS_train_y = train_y 

from sklearn.naive_bayes import MultinomialNB
MNB = MultinomialNB()
MNB.fit(MMS_train_x,MMS_train_y)
MMS_data = MMS.fit_transform (data[prediction_var])
MNB_pred = MNB.predict(MMS_data )
print (MNB_pred)
print (pd.DataFrame(MNB_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (data['Status'],MNB_pred))
print('\nClassification Report')
print(classification_report (data['Status'],MNB_pred))
print('Confusion Matrix')
print (confusion_matrix (data['Status'],MNB_pred))



[10 10 10 ... 10 10 10]
        0
0        
3     801
10  25336

 Accuracy Score
0.41615334583157976

Classification Report


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       1.00      0.12      0.21      6766
           4       0.00      0.00      0.00      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.00      0.00      0.00         6
           9       0.00      0.00      0.00      6965
          10       0.40      1.00      0.57     10076

    accuracy                           0.42     26137
   macro avg       0.13      0.10      0.07     26137
weighted avg       0.41      0.42      0.27     26137

Confusion Matrix
[[    0     0     0     0     0     0     0     0     0     0   217]
 [    0     0     0     0     0     0     0     0     0     0   152]
 [    0     0     0     0     0 

In [21]:
from sklearn.svm import SVC
SVM_SIG = SVC (kernel = 'sigmoid')
SVM_SIG.fit(train_x,train_y)
SVM_SIG_pred = SVM_SIG.predict(data[prediction_var])
print (SVM_SIG_pred)
print (pd.DataFrame(SVM_SIG_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (data['Status'],SVM_SIG_pred))
print('\nClassification Report')
print(classification_report (data['Status'],SVM_SIG_pred))
print('Confusion Matrix')
print (confusion_matrix (data['Status'],SVM_SIG_pred))



[10 10 10 ...  3  3  3]
        0
0        
3    4350
4    2037
9    6946
10  12804

 Accuracy Score
0.2898190304931706

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       0.00      0.00      0.00      6766
           4       0.00      0.00      0.00      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.00      0.00      0.00         6
           9       0.31      0.31      0.31      6965
          10       0.42      0.54      0.47     10076

    accuracy                           0.29     26137
   macro avg       0.07      0.08      0.07     26137
weighted avg       0.25      0.29      0.27     26137

Confusion Matrix
[[   0    0    0  217    0 

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [22]:
from sklearn.svm import SVC
SVM_LIN = SVC (kernel = 'linear')
SVM_LIN.fit(train_x,train_y)
SVM_LIN_pred = SVM_LIN.predict(data[prediction_var])
print (SVM_LIN_pred)
print (pd.DataFrame(SVM_LIN_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (data['Status'],SVM_LIN_pred))
print('\nClassification Report')
print(classification_report (data['Status'],SVM_LIN_pred))
print('Confusion Matrix')
print (confusion_matrix (data['Status'],SVM_LIN_pred))



[10 10 10 ...  9  4  4]
        0
0        
3    6783
4    2141
8       7
9    7033
10  10173

 Accuracy Score
0.9541645942533573

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       1.00      1.00      1.00      6766
           4       0.71      0.83      0.77      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.71      0.83      0.77         6
           9       0.93      0.94      0.94      6965
          10       0.99      1.00      1.00     10076

    accuracy                           0.95     26137
   macro avg       0.40      0.42      0.41     26137
weighted avg       0.94      0.95      0.95     26137

Confusion Matrix
[[    0     0    

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [23]:
from sklearn.svm import SVC
SVM_RBF = SVC (kernel = 'rbf')
SVM_RBF.fit(train_x,train_y)
SVM_RBF_pred = SVM_RBF.predict(data[prediction_var])
print (SVM_RBF_pred)
print (pd.DataFrame(SVM_RBF_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (data['Status'],SVM_RBF_pred))
print('\nClassification Report')
print(classification_report (data['Status'],SVM_RBF_pred))
print('Confusion Matrix')
print (confusion_matrix (data['Status'],SVM_RBF_pred))



[10 10 10 ...  4  4  4]
        0
0        
3    5219
4    3259
10  17659

 Accuracy Score
0.6367984083865784

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       0.99      0.76      0.86      6766
           4       0.51      0.92      0.66      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.00      0.00      0.00         6
           9       0.00      0.00      0.00      6965
          10       0.56      0.97      0.71     10076

    accuracy                           0.64     26137
   macro avg       0.19      0.24      0.20     26137
weighted avg       0.51      0.64      0.54     26137

Confusion Matrix
[[   0    0    0    0  217    0    0 

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [24]:
from sklearn.tree import DecisionTreeClassifier
TREE = DecisionTreeClassifier (criterion = 'entropy')
TREE.fit(train_x,train_y)
TREE_pred = TREE.predict(data[prediction_var])
print (TREE_pred)
print (pd.DataFrame(TREE_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (data['Status'],TREE_pred))
print('\nClassification Report')
print(classification_report (data['Status'],TREE_pred))
print('Confusion Matrix')
print (confusion_matrix (data['Status'],TREE_pred))



[10 10 10 ...  9  4  4]
        0
0        
0       6
2      23
3    6784
4    2062
5       2
7       9
8       6
9    7125
10  10120

 Accuracy Score
0.9587940467536442

Classification Report


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           0       0.50      0.01      0.03       217
           1       0.00      0.00      0.00       152
           2       0.91      0.19      0.32       110
           3       1.00      1.00      1.00      6766
           4       0.74      0.84      0.79      1828
           5       1.00      0.33      0.50         6
           6       0.00      0.00      0.00         4
           7       0.78      1.00      0.88         7
           8       0.83      0.83      0.83         6
           9       0.94      0.96      0.95      6965
          10       0.99      1.00      1.00     10076

    accuracy                           0.96     26137
   macro avg       0.70      0.56      0.57     26137
weighted avg       0.95      0.96      0.95     26137

Confusion Matrix
[[    3     0     0     0   205     0     0     0     0     9     0]
 [    0     0     0     6     0     0     0     0     0   123    23]
 [    0     0    21    11     7 

In [25]:
from sklearn.tree import DecisionTreeClassifier
TREE_GINI = DecisionTreeClassifier (criterion = 'gini')
TREE_GINI.fit(train_x,train_y)
TREE_GINI_pred = TREE_GINI.predict(data[prediction_var])
print (TREE_GINI_pred)
print (pd.DataFrame(TREE_GINI_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (data['Status'],TREE_GINI_pred))
print('\nClassification Report')
print(classification_report (data['Status'],TREE_GINI_pred))
print('Confusion Matrix')
print (confusion_matrix (data['Status'],TREE_GINI_pred))



[10 10 10 ...  9  4  4]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


        0
0        
0       6
2      26
3    6784
4    2062
5       2
7      11
8       6
9    7125
10  10115

 Accuracy Score
0.9586027470635498

Classification Report
              precision    recall  f1-score   support

           0       0.50      0.01      0.03       217
           1       0.00      0.00      0.00       152
           2       0.81      0.19      0.31       110
           3       1.00      1.00      1.00      6766
           4       0.74      0.84      0.79      1828
           5       1.00      0.33      0.50         6
           6       0.00      0.00      0.00         4
           7       0.64      1.00      0.78         7
           8       0.83      0.83      0.83         6
           9       0.94      0.96      0.95      6965
          10       0.99      1.00      1.00     10076

    accuracy                           0.96     26137
   macro avg       0.68      0.56      0.56     26137
weighted avg       0.95      0.96      0.95     26137

Confusion Matrix
[

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [26]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=100, criterion='entropy')
RF.fit(train_x,train_y)
RF_pred = RF.predict(data[prediction_var])
print (RF_pred)
print (pd.DataFrame(RF_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (data['Status'],RF_pred))
print('\nClassification Report')
print(classification_report (data['Status'],RF_pred))
print('Confusion Matrix')
print (confusion_matrix (data['Status'],RF_pred))


[10 10 10 ...  9  4  4]
        0
0        
0       4
2      21
3    6785
4    2043
5       2
7       8
8       5
9    7139
10  10130

 Accuracy Score
0.9591383861958144

Classification Report
              precision    recall  f1-score   support

           0       0.50      0.01      0.02       217
           1       0.00      0.00      0.00       152
           2       0.95      0.18      0.31       110
           3       1.00      1.00      1.00      6766
           4       0.75      0.84      0.79      1828
           5       1.00      0.33      0.50         6
           6       0.00      0.00      0.00         4
           7       0.88      1.00      0.93         7
           8       1.00      0.83      0.91         6
           9       0.93      0.96      0.95      6965
          10       0.99      1.00      1.00     10076

    accuracy                           0.96     26137
   macro avg       0.73      0.56      0.58     26137
weighted avg       0.95      0.96      0.95     2

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [27]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=100, criterion='gini')
RF.fit(train_x,train_y)
RF_pred = RF.predict(data[prediction_var])
print (RF_pred)
print (pd.DataFrame(RF_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (data['Status'],RF_pred))
print('\nClassification Report')
print(classification_report (data['Status'],RF_pred))
print('Confusion Matrix')
print (confusion_matrix (data['Status'],RF_pred))







[10 10 10 ...  9  4  4]
        0
0        
0       6
2      21
3    6785
4    2042
5       2
7       8
8       5
9    7139
10  10129

 Accuracy Score
0.9591001262577955

Classification Report
              precision    recall  f1-score   support

           0       0.50      0.01      0.03       217
           1       0.00      0.00      0.00       152
           2       0.95      0.18      0.31       110
           3       1.00      1.00      1.00      6766
           4       0.75      0.84      0.79      1828
           5       1.00      0.33      0.50         6
           6       0.00      0.00      0.00         4
           7       0.88      1.00      0.93         7
           8       1.00      0.83      0.91         6
           9       0.93      0.96      0.95      6965
          10       0.99      1.00      1.00     10076

    accuracy                           0.96     26137
   macro avg       0.73      0.56      0.58     26137
weighted avg       0.95      0.96      0.95     2

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
